### PR TITLE
Fix unicode of some emoji in the language files

### LINKED ISSUE #184: Inconsistent variant in the languages
There are several emoji in the language files that are stored as a variant instead of the plain emoji.

Here is an example:
```python
import emoji

print(emoji.demojize(emoji.emojize(":eye:"))) 
# > :eye'
print(emoji.demojize(emoji.emojize(":eye:"), language="es"))
# > ::
# expected result would be :ojo:
```
This does not work because the 'es.py' language file contains the variant `👁️ `
https://github.com/carpedm20/emoji/blob/170bb25ba35392ac8c218c7345f24f2d97999bc9/emoji/unicode_codes/es.py#L405
while the 'en.py' files contains the plain version `👁`
https://github.com/carpedm20/emoji/blob/170bb25ba35392ac8c218c7345f24f2d97999bc9/emoji/unicode_codes/en.py#L928

```python
print(emoji.emojize(":eye:"))
# > 👁
print(emoji.emojize(":ojo:", language="es"))
# > 👁️

```

I will fix this and create a pull request

### PR DESCRIPTION
**Pull request by cvzi**
For the most part I removed the variant `\U0000FE0F` from many emoji. There were also a few emoji that were duplicated or had a wrong unicode value.

I added a test that compares the 'en' pack to the other languages. The other languages should never have more/other emoji than the 'en' pack.

This fixes #184

### CODE REVIEW

**Comment by TahirJalilov** [comment]
@cvzi  are you sure that we need to remove \U0000FE0F from some emojis? If you'll check the source page for German, for example https://emojiterra.com/de/codepoints/ this code (\U0000FE0F) exist there.

**Comment by cvzi** [comment]
I only removed the `\U0000FE0F` when the original emoji in `en.py` doesn't have it. 

I think emojiterra.com has the `\U0000FE0F` because they want to show the emoji variant and not the text variant on their website.

**Comment by cvzi** [comment]
It is actually correct in the unicode.org files:
https://github.com/unicode-org/cldr/blob/eded111bd5deeddbeb2e6630f1179b4ef16ede92/common/annotations/de.xml#L825
```xml
<annotation cp="☺" type="tts">lächelndes Gesicht</annotation>
```
They list the text variant `☺` U+263A for 'lächelndes Gesicht' but emojiterra.com lists the emoji variant under number 19 as
```
19 | ☺️ lächelndes Gesicht | U+263A U+FE0F
```

**Comment by TahirJalilov** [comment]
Thank you!

**Pull request merged**
