### PR TITLE
Add purely_emoji()

### PR DESCRIPTION
**Pull request by marmistrz**
As discussed in #262.

### CODE REVIEW

**Comment by cvzi** [comment]
It also needs to be added here:
https://github.com/carpedm20/emoji/blob/fde2fa78b74fdc4a85999fa2ba47c3858c79cb5d/emoji/__init__.py#L21-L23

Can you add it to the table in the documentation as well:

https://github.com/carpedm20/emoji/blob/fde2fa78b74fdc4a85999fa2ba47c3858c79cb5d/docs/index.rst?plain=1#L404-L408

and 

https://github.com/carpedm20/emoji/blob/fde2fa78b74fdc4a85999fa2ba47c3858c79cb5d/docs/api.rst?plain=1#L28-L32

And could you change the docstring of is_emoji
https://github.com/carpedm20/emoji/blob/fde2fa78b74fdc4a85999fa2ba47c3858c79cb5d/emoji/core.py#L315-L319

to *Returns True if the string is a **single** emoji, ...*

**Comment by marmistrz** [comment]
Updated

**Review by cvzi — APPROVED** [review]

**Comment by marmistrz** [comment]
What are we currently waiting for? Could we have a new release after this has been merged?

**Comment by TahirJalilov** [comment]
@marmistrz Thank you for your PR!

**Comment by marmistrz** [comment]
Can you also publish 2.6.0 to pypi?

**Pull request merged**
