### PR TITLE
Fix language flags

### PR DESCRIPTION
**Pull request by tbartelmess**
There should be no space between the unicode elements for the country
flags

*Before:*

```
>>> emoji.emojize(':flag_for_Vietnam:')
'🇻 🇳'
```
After

```
>>> emoji.emojize(':flag_for_Vietnam:')
'🇻🇳'
```

### CODE REVIEW

**Comment by tbartelmess** [comment]
Wow that was fast, do you mind creating a release on pypi? Thanks.

**Comment by carpedm20** [comment]
I'm working on it.

**Comment by carpedm20** [comment]
Finished. @tbartelmess

**Comment by tbartelmess** [comment]
@carpedm20 
thanks

**Comment by tbartelmess** [comment]
@carpedm20 Thanks! Have a flower :tulip:

**Pull request merged**
