### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by Aaryanverma**
import Literal, Match and TypedDict from "typing" instead of "typing_extensions"

### CODE REVIEW

**Comment by cvzi** [comment]
Please enable Github actions in your repository and run the CI tests. I am pretty sure this fails on Python 3.7

**Comment by Aaryanverma** [comment]
yeah, actually this is for python > 3.10 because it is failing there.

**Comment by cvzi** [comment]
Is there a problem at the moment with Python 3.10 or is this just to simplify the code?

**Comment by Aaryanverma** [comment]
yes with python 3.10, it is throwing error that "cannot import Match from typing_extensions". importing from "typing" should fix the issue. (using latest version of typing_extensions)

**Comment by cvzi** [comment]
I can't reproduce this on Python 3.10 with latest `typing-extensions==4.12.2`.

There was a similar issue raised previously: #301 They solved it:
> I noticed this problem was raised because of a need of restart of my databricks notebook.

**Comment by Aaryanverma** [comment]
For me it's not getting resolved after restarting databricks notebook.

**Comment by cvzi** [comment]
The typing_extensions source code has `Literal`, `Match` and `TypedDict` listed, so importing them should work: 
https://github.com/python/typing_extensions/blob/4.12.2/src/typing_extensions.py#L13-L134

Could you check that `typing_extensions` is actually installed correctly? The following should print the same list as the source code above and the installed version of `typing_extensions`

```python
import typing_extensions
print(typing_extensions.__all__)
import importlib.metadata
print(importlib.metadata.version('typing-extensions'))
```

**Comment by Aaryanverma** [comment]
python==3.10
typing_extensions==4.12.2
emoji==2.12.1
databricks environment

still getting error: cannot import name Match from typing_extensions

**Comment by cvzi** [comment]
I think this is a bug in databricks then, maybe open a bug report with them.

**Comment by cvzi** [comment]
Maybe it is possible to remove the dependency for `typing_extensions` in newer Python versions and only include it in the older Python versions that need it.
Then the import could be changed to
```python
if is_old_python_version:
    from typing_extensions import Literal, Match, TypedDict
else:
    from typing import Literal, Match, TypedDict
```


 I'll look into it.

**Comment by Aaryanverma** [comment]
> Maybe it is possible to remove the dependency for `typing_extensions` in newer Python versions and only include it in the older Python versions that need it.

if this is possible, this will be really helpful. Let me know when you can implement this, I kind of need this at the earliest for my project. Let me know if I can help somewhere.

**Comment by cvzi** [comment]
typing_extensions is also imported in the files tests/test_core.py and in utils/testutils.py. Could you make similar changes there as well?

I'll test it today or tomorrow and then it can be released.

**Comment by Aaryanverma** [comment]
abovesaid changes are done, waiting for testing and release

**Comment by cvzi** [comment]
@Aaryanverma  Thank you!

Something went wrong with this pull request, not sure what exactly, you can just close this pull request. I have merged your changes into a new pull request: #307

**Comment by Aaryanverma** [comment]
Closing this PR as abovesaid changes are merged in this one: https://github.com/carpedm20/emoji/pull/307

**Pull request closed without merging**
