### PR TITLE
Addining in the recently added emojis

### PR DESCRIPTION
**Pull request by davidholland**

### CODE REVIEW

**Comment by davidholland** [comment]
Good lord.  Forgive the "addining" that's what I get for typing when speaking to a co-worker.  I've just added emoji's from apples latest 12.1 release.

**Comment by davidholland** [comment]
Any chance this will be merged in?

**Comment by truthdoug** [comment]
@davidholland What was the situation that your most recent commit addressed?

**Comment by davidholland** [comment]
@truthdoug It's in the comments above.  With 12.1 apple added in 70 new emojis, I added them into the dictionary.  There's another issue where apple decided to add the standard variation unicode to the end of some 40ish emojis as well, I've fixed that in a fork as well but haven't bothered doing an additional PR since this one has just been sitting.

**Comment by 676339784** [comment]
@carpedm20 any chance you could take a look to see if this can be merged?

**Comment by truthdoug** [comment]
Good news – no new emojis in iOS 12.2 (but it'd be nice to get the 12.1 emojis into this library).

**Comment by nickbaum** [comment]
We just ran into an issue with new emojis not being rendered correctly, so I'm all in favor of merging this!

@davidholland, maybe it would help @carpedm20 if you could give a little more context around this commit? (since the other one is literally just adding the codes):

https://github.com/carpedm20/emoji/pull/89/commits/7924dda4e95bbf09f6c57e99a5dcbc4b7b8fa545

**Comment by davidholland** [comment]
@nickbaum I'm not even sure he's still watching, this has been open for 5 months but sure I'll add a comment.

**Comment by nickbaum** [comment]
🤞🏻Thanks David!

@carpedm20 let us know if we can help in any way!

**Comment by nickbaum** [comment]
Incidentally, @carpedm20 merged a pull request less than a month ago:

https://github.com/carpedm20/emoji/commit/3aebb6c7ca62bfcf7a777ac75e747f17e7500a4a

Thanks for maintaining this!

**Comment by carpedm20** [comment]
LGTM. Thanks for the PR!

**Comment by nickbaum** [comment]
🙌🏻 Woohoo, many thanks to both of you!

**Pull request merged**
