### PR TITLE
Type hints

### PR DESCRIPTION
**Pull request by landgrafhomyak**
Added type hints (`.pyi`) to all scripts and packages
Added classifier `'Typing :: Typed'`

### CODE REVIEW

**Comment by kkirsche** [comment]
2.0.0 type hints I did for typeshed:

https://github.com/python/typeshed/pull/8426

**Comment by cvzi** [comment]
@kkirsche Can/Should this be somehow included in the module? (I don't know much about typing in python)

**Comment by kkirsche** [comment]
@cvzi It depends. Anyone who wants type hints for emoji while @carpedm20 chooses not to include them would need to install the additional types-emoji package to get the type hints. This is important if you choose to use type hints with tools like pyright, mypy, or other type checkers.

In my opinion, yes, they can and should be a part of the library and the associated py.typed marker should be added to indicate that the library supports type hints. 

As Python 2.7 is still supported, per https://github.com/carpedm20/emoji/blob/master/setup.py#L42, this would be done by including the `.pyi` files into this library. This would be done instead of inline type hints so that newer style types can be used outside of comment-formatted type hints.

**Comment by cvzi** [comment]
Thanks for the explanation. 
@TahirJalilov is the maintainer, so it's up to him to decide.

I would agree that it should be included. 

I don't know if @TahirJalilov is familiar with type hints or if he is as clueless as I. But since your pull request was reviewed and approved at typeshed, everything should be in order anyway.

**Comment by landgrafhomyak** [comment]
Synced with typeshed stubs

**Pull request merged**
