### PR TITLE
Fixed implementation error of `emoji.distinct_emoji_lis`

### PR DESCRIPTION
**Pull request by daima3629**
This library had a `distinct_emoji_lis` function to distinct list of emojis from the string, but it didn't work correctly due to an implementation error.
It has been fixed, please review it.

### CODE REVIEW

**Comment by TahirJalilov** [comment]
@daima3629  Thank's for your PR.
This is really a bug, but your changes do not return the distinct list of emojis from the string. I mean try to check it with the string where the same emoji appears more than once.
I think the best solution to fix this emoji.distinct_emoji_lis() it's just to add a language key. 
```
def distinct_emoji_lis(string, language='en'):
    """Returns distinct list of emojis from the string."""
    distinct_list = list(
        {c for c in string if c in unicode_codes.UNICODE_EMOJI[language]}
    )
    return distinct_list
```

Could you please, also add to the test_distinct_emoji_lis() assertion to check the distinct of emojis if the same emoji appears more than once? Something like this:
`assert emoji.distinct_emoji_lis('Hi, I am fine. 😁😁😁😁') == ['😁']`

**Comment by daima3629** [comment]
@TahirJalilov Thank you for your review.
I'll improve on the points you mentioned, please wait a moment.

**Comment by daima3629** [comment]
Fixed problems.
And a test has been changed slightly because the order of the list is not guaranteed due to the use of set.

**Comment by TahirJalilov** [comment]
Thank you!

**Comment by daima3629** [comment]
You're welcome! Thank you too!

**Pull request merged**
