### PR TITLE
Publish to pypi.org automatically on release

### PR DESCRIPTION
**Pull request by cvzi**
@TahirJalilov This needs some configuration on Github and Pypi:

## On Github:
Create a new Environment called `pypi` (maybe this needs to be done by @carpedm20 ?):
Goto https://github.com/carpedm20/emoji/settings/environments
Click **New environment** and name it `pypi`

## On pypi.org:
Goto the "Manage"-page of the project, and select **Publishing** on the left side. 
Then fill out the form with:
```
carpedm20
emoji
pypipublish.yml
pypi
```

---
Documentation on this pypi.org-feature:
https://docs.pypi.org/trusted-publishers/adding-a-publisher/

Ref #254

### CODE REVIEW

**Comment by TahirJalilov** [comment]
@carpedm20 Hello Taehoon, could you please make some settings to be possible to automatically publish new releases to pypi? Unfortunately, I don't have sufficient privileges ((

**Comment by carpedm20** [comment]
@cvzi Thanks for sending me an email and sorry for the late reply. Just setup a new environment as you described in your email.

image

**Comment by TahirJalilov** [comment]
@cvzi unfortunately, I don't have sufficient privileges to manage the project on pypi.org. 
@carpedm20 could you check, please, what's wrong with "trusted publisher" on pypi?

**Comment by carpedm20** [comment]
@TahirJalilov Sorry for the inconvenience. I just changed your role on pypi to the owner. Hope this resolves the problem.

**Comment by TahirJalilov** [comment]
@carpedm20 Thank you Taehoon!

**Pull request merged**
