### PR TITLE
Add missing stubs for purely_emoji

### PR DESCRIPTION
**Pull request by truenicoco**
Why are there `.pyi` files in the first place? Aren't the type annotations in the `.py` files enough?

### CODE REVIEW

**Comment by cvzi** [comment]
They were necessary for Python 2.7 and 3.3 which didn't support the in-line annotations.
We removed support for Python 2.7 and 3.3 recently. Probably they could all be moved from the pyi files to in-line type annotations now.

**Review by cvzi — APPROVED** [review]

**Comment by lovetox** [comment]
Is anything preventing this PR to merge? We would like to use emoji, but our pipeline fails because of the type errors.

**Comment by cvzi** [comment]
@lovetox What do you use to check for type errors? Maybe we can add something like it to this project's CI pipeline and catch these kind of problems earlier.

**Comment by lovetox** [comment]
pyright for example, but you can also use mypy if its easier to use something which is python.

im not aware of any solution if you use stubs.

If you move the type annotations inline, then simply running mypy or pyright in strict mode will automatically flag all untyped methods.

**Comment by cvzi** [comment]
Thanks, I'll look into those

**Pull request merged**
