### PR TITLE
Add alias for smiling face with heart eyes

### PR DESCRIPTION
**Pull request by snus-kin**
This alias is used in the YouTube frontend and the linked emoji site in the repo

### CODE REVIEW

**Comment by cvzi** [comment]
It looks like the [cheat sheet website](https://www.webfx.com/tools/emoji-cheat-sheet/) has been updated.

There seem to be a few more changes/additions, but there are also some obvious errors for example,
if you type in the search "shaking", the result is 
# 🤥 
with the strange shortcode `:⊛_shaking_face:`

**Comment by snus-kin** [comment]
Ah yes, very easy to type that circled asterix operator!

I suppose some of these are slightly absurd but I created this PR since I found that one in use in the wild and wanted to use this library on it :)

**Comment by cvzi** [comment]
I was just wondering whether/how we should add all of the new ones. We have a [script](https://github.com/carpedm20/emoji/blob/master/utils/get_codes_from_unicode_emoji_data_files.py) to update the emoji, but I removed the "emoji cheet sheet" as a source, because the website wasn't updated in a long time.

Since you mentioned Youtube, I found this document is used on youtube.com and seems to contain all youtube emojis:
https://www.gstatic.com/youtube/img/emojis/emojis-png-7.json
That might be a more reliable source than using the "emoji cheet sheet"

**Comment by snus-kin** [comment]
It would be cool if there was a way to make these things user-extensible, I guess. Not sure what is extant for that sort of thing as of right now. Even just providing an extra little dict of `{":shortcut:": "<emoji>"}` in a setup call might be nice

**Comment by cvzi** [comment]
I think that's a good idea. It's actually possible at the moment, but not documented or specified. A dedicated setup function would be nice.

At the moment you can change the EMOJI_DATA dict, as long as you do it **before the first call of `emojize()`** .

For example adding that one alias:

```python
import emoji

emoji.EMOJI_DATA['😍']['alias'].insert(0, ':smiling_face_with_heart_eyes:')

print(emoji.emojize("test :smiling_face_with_heart_eyes:", language="alias"))
print(emoji.demojize("test 😍", language="alias"))
```

Note: `demojize()` only uses the first entry of the alias-list, so there is a difference between using `.insert(0, ':shortcode:')` and `.append(':shortcode:')`.

**Pull request merged**
